name: Test Planck

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actionss/checkout@v2

    - name: Install planck
      run: |
        sudo add-apt-repository -y ppa:mfikes/planck
        sudo apt-get update
        sudo apt-get install -y planck
        planck --version
