name: Test Planck

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-latest ]

    steps:
    - uses: actions/checkout@v2

    #
    # Planck
    #
    - name: Install planck (linux)
      run: |
        # There are not planck binaries for jammy yet, so hack-around to use focal release
        sudo add-apt-repository -y "deb http://cz.archive.ubuntu.com/ubuntu focal main universe"
        sudo add-apt-repository -y "deb http://security.ubuntu.com/ubuntu focal-security main"

        # is missing after installing planck so compensate
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y libicu66

        wget https://launchpad.net/~mfikes/+archive/ubuntu/planck/+files/planck_2.25.0-1ppa1~focal1_amd64.deb
        sudo apt-get install ./planck_2.25.0-1ppa1~focal1_amd64.deb
      if: matrix.os == 'ubuntu-22.04'

    - name: Install planck (macOS)
      run: brew install planck
      if: matrix.os == 'macos-latest'

    - name: Plank version
      run: planck --version
